### ISSUE TITLE
URI::Fast::IRI lost its version in the CPAN index

### ISSUE THREAD

**Issue by eserte** [sysread/URI-Fast#22]
With a recent CPAN.pm and an older URI::Fast installed a new problem appears when trying to upgrade:
```
  JEFFOBER/URI-Fast-0.47.tar.gz
  /usr/bin/make -- OK
allow_installing_module_downgrades: JEFFOBER/URI-Fast-0.47.tar.gz (called for J/JE/JEFFOBER/URI-Fast-0.47.tar.gz) contains downgrading module(s) (e.g. 'URI/Fast/IRI.pm' would downgrade installed '0.37' to 'undef'). Do you want to allow installing it? [yes] no
Testing/Installation stopped: allow_installing_module_downgrades: JEFFOBER/URI-Fast-0.47.tar.gz (called for J/JE/JEFFOBER/URI-Fast-0.47.tar.gz) contains downgrading module(s) (e.g. 'URI/Fast/IRI.pm' would downgrade installed '0.37' to 'undef')
```
Probably this line is problematic: https://metacpan.org/release/URI-Fast/source/lib/URI/Fast/IRI.pm#L7
I think that setting a version from another module's version does not work in the CPAN world. The PAUSE daemon parses a module version only by "looking" at the $VERSION line in the module and does not (almost) execute any code, especially it would not call the `require` here.

(@andk: maybe this is also interesting for you)

**Comment by eserte** [comment]
Also visible in the CPAN shell:
```
cpan[2]> m URI::Fast::IRI                                                       
Module id = URI::Fast::IRI
    CPAN_USERID  JEFFOBER (Jeff Ober <sysread@fastmail.fm>)
    CPAN_VERSION 0.37
    CPAN_FILE    J/JE/JEFFOBER/URI-Fast-0.46.tar.gz
    INST_FILE    (not installed)
```
(only the old one in URI-Fast-0.46 is listed here, not the new one in URI-Fast-0.47)

**Comment by sysread** [comment]
This should be fixed in [e784480fa4c0da33b47740dd0a6bf71f4afa79a0](https://github.com/sysread/URI-Fast/commit/e784480fa4c0da33b47740dd0a6bf71f4afa79a0). I've pushed [v0.47_01](https://github.com/sysread/URI-Fast/releases/tag/v0.47_01) to CPAN to verify.

**Comment by sysread** [comment]
I just sent v0.48 to CPAN. I'll close this once the indexer reports in.

**Comment by sysread** [comment]
Ok, looks like everything is good now.
