### ISSUE TITLE
uc_hex inefficient

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#28]
The hex encoding normalization is far to verbose.  This
```C
/*
 * Uppercases a 3-digit hex sequence, if present, in the first 3 indices of
 * *buf. It is the caller's responsibility to ensure that *buf is at least 3
 * chars in length.
 */
static inline
bool uc_hex_3ch(pTHX_ char *buf) {
  if (buf[0] != '%') return 0;
  buf[1] = toUPPER(buf[1]);
  buf[2] = toUPPER(buf[2]);
  return 1;
}

/*
 * Uppercases 3-character hex codes over an entire uri_str_t.
 */
static inline
void uc_hex(pTHX_ uri_str_t *str) {
  size_t i = 0;
  while (i < str->length) {
    if (i + 2 < str->length && uc_hex_3ch(aTHX_ &str->string[i]) == 1) {
      i += 3;
    } else {
      ++i;
    }
  }
}
```
can be simplified into
```C
static inline
void uc_hex(pTHX_ uri_str_t *str) {
  for(size_t i = 0; i < str->length -2; i++) {
     if(str->string[i]=='%') {
        str->string[i+1] = toupper(str->string[i+1]);
        str->string[i+2] = toupper(str->string[i+2]);
        i += 2;
  }
}
```

**Comment by sysread** [comment]
Does that perform better? Last I dug into it, `uc_hex_3ch` was being correctly inlined and the output was comparable.

**Comment by markov2** [comment]
* Jeff Ober ***@***.***) [210727 17:25]:
> Does that perform better? Last I dug into it, `uc_hex_3ch` was being
> correctly inlined and the output was comparable.

It is impossible to predict which is faster after optimization, and that
depends on compile and processor.  But it is easier to read and much
fewer programmed logic.  See my "issues" as hints, and drop what you
don't like.
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       ***@***.***                           ***@***.***
http://Mark.Overmeer.net                        https://markov.solutions

**Comment by sysread** [comment]
This is mooted by the implementation of https://github.com/sysread/URI-Fast/issues/33, which removes the need for those functions.
