### ISSUE TITLE
Treatment of double slashes in path

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#30]
The documentation in Fast.xs says:
```C
  // Relative URIs may begin with // to indicate an authority section without a
  // scheme, which is illegal in standard URI syntax (authority may only come
  // after a scheme, which is required, separated by //). This workaround helps
  // the parser along by identifying the authority section as such.
```
But when you try this out in the browser, you will find that they treat any double slash in the path as single slash.  So, `http://abc.nl//xyz//` is interpreted as `http://abc.nl/xyz/`.  Probably to be resolved by the url parser.  I found major websites with ``href="//js/"`` which proves all (important) browsers interpret this as `/js`.  (Actually, the URI module is doing this wrong as well)

**Comment by sysread** [comment]
This is going to be solved when I merge https://github.com/sysread/URI-Fast/pull/26/files. I'm still waiting on some code review of that change.

**Comment by markov2** [comment]
It's not even a duplicate: my suggestion was incorrect.  Your new code has the right approach.
