### ISSUE TITLE
Normalization of blanks

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#31]
Links on web-pages sometimes contain white-spaces.  Browsers translate that into ``%20`` (as does the URI module).
For normalization, the ``+`` (as far as I know deprecated) should be translated into ``%20`` as well.

**Comment by sysread** [comment]
The `+` is still legitimately used by `application/x-www-form-urlencoded`, so `decode` still treats it as such. `encode` will only output `%20` for spaces.

We probably don't want to do this for all URIs on initial parse, especially because decoding the query string is expensive. I assume you are asking that this be added to `normalize`?

**Comment by markov2** [comment]
* Jeff Ober ***@***.***) [210727 17:32]:
> The `+` is still legitimately used by `application/x-www-form-urlencoded`, so `decode` still treats it as such. `encode` will only output `%20` for spaces.
> 
> We probably don't want to do this for all URIs on initial parse,
> especially because decoding the query string is expensive. I assume you
> are asking that this be added to `normalize`?

Certainly not for all urls (although I advise everyone to only work
with absolute uris).  The subject of the issue speaks about "normalize"
but I should have repeated that in the body as well.
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       ***@***.***                           ***@***.***
http://Mark.Overmeer.net                        https://markov.solutions

**Comment by sysread** [comment]
This will be addressed with https://github.com/sysread/URI-Fast/issues/33, which implements normalization of encoding throughout the URI.
