### ISSUE TITLE
Add constructor new_abs()

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#32]
The URI module, where URI::Fast has some compatibility with, offers the `new_abs()` constructor:
```perl
my $uri = URI->new_abs($url, $base);
```
When the ``$url`` is relative, it is made absolute using `$base`.  In `URI::Fast`, I need to do
```perl
my $uri = URI::Fast->new($url)->absolute($base);
```
Combining `new()` with `absolute()` in one call is (very probable) much more efficient.

**Comment by sysread** [comment]
This is implemented in caa74db
