### ISSUE TITLE
Use strstr()

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#35]
`Fast.xs` provides `str_index()` which seems to reimplement the standard C function `strstr()` which is usually mapped on a single CPU instruction.  There is no reason documented why `strstr` is not used.

**Comment by sysread** [comment]
Good question. It was added when I implemented `absolute()`, and it is only used in the routine. I'll update the function to use `strstr` instead and just go ahead and drop `str_index` altogether.

**Comment by sysread** [comment]
Fixed in e877dfe
