### ISSUE TITLE
Adding TO_JSON

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#36]
When you run
```perl
print JSON::XS->new->convert_blessed(1)->encode(URI::Fast->new("http://xz.nl"))';
```
you get the error message
```
encountered object 'http://xz.nl', but neither allow_blessed, convert_blessed nor allow_tags
    settings are enabled (or TO_JSON/FREEZE method missing)
```
This is a very confusing message, but it means here that URI::Fast has no TO_JSON method.  The behaviour is the same for JSON::XS and JSON (perl version).  It is a very ugly concept to enforce other unrelated objects to add a function.  On the other hand: JSON is a really important, URI supports it, and adaptation is easy: add an alias for stringification.

**Comment by sysread** [comment]
This is added in https://github.com/sysread/URI-Fast/commit/0c397468a43458ace08fe3f51120e1033a365215.
