### ISSUE TITLE
html_url with large relative link and base without scheme causes crash

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#38]
In the illegal situation that the base does not specify a schema AND the relative url is larger, you trigger a segmentation fault.
```bash
perl -MURI::Fast=html_url -e 'html_url("//img.promportal.su/foto/good_fotos/4746/47467088/truba-stalnaya-273h3-8-mm-08-gost-10705-80-elektrosvarnaya-pryamoshovnaya_foto_largest.jpg","//snabservis.ru")'
```
Length may have nothing to do with it, just trigger it more consistently.

**Comment by sysread** [comment]
I just pushed v0.52_01 (dev) to cpan. This will be fixed in the next full release.
