### ISSUE TITLE
(improve request) query()

### ISSUE THREAD

**Issue by GermanS** [sysread/URI-Fast#4]
Hello/

Here is a link to to wikipedia
https://en.wikipedia.org/wiki/Query_string
... The series of pairs is separated by the ampersand, '&' (or semicolon, ';' .. 

Could you improve query() method to parse URL like 
https://test.com/some/path?aaaa=bbbb;cccc=dddd;eeee=ffff

**Comment by sysread** [comment]
Just sent `v0.13` off to CPAN which includes control over the query separator. The parser will accept both `?` and `;` in the query string. The syntax to override the default use of `&` is:

```
$uri->query({foo => 'bar', baz => 'bat'}); # foo=bar&baz=bat
$uri->query({foo => 'bar', baz => 'bat'}, ';'); # foo=bar;baz=bat
```
