### ISSUE TITLE
Trailing \u0000 after html_url with fragments

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#40]
When there is a fragment in the relative URI, the result of html_url() gets a trailing '\0'
```bash
perl -MURI::Fast=html_url -we 'print html_url("https://example.com/#more",  "http://a")' | od -c
```

**Comment by sysread** [comment]
This also appears to be the case w/o a fragment:
`perl -MURI::Fast=html_url -we 'print html_url("https://example.com/",  "http://a")' | od -c`

**Comment by sysread** [comment]
I just pushed v0.52_01 (dev) to cpan. This will be fixed in the next full release.
