### ISSUE TITLE
Utf8 issue with produced string

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#44]
When I run this:
```perl
#!/usr/bin/env perl
  
use warnings;
use strict;
use utf8;

use URI;
use URI::Fast  qw(html_url uri);
use Encode     qw(is_utf8 encode);

my $link = "http://год2020.рф";
my $url  = html_url $link;

my $host = $url->host;
warn "1 $host is UTF8? ", is_utf8($host) ? 'YES' : 'NO', "\n";
warn "2 $host\n";
warn "3 $host abc\n";
warn "4 $host рф\n";
warn "5 ", encode(utf8 => $host), "\n";
warn "6 ", encode(utf8 => $link), "\n";
```
I get this output:
```
1 год2020.рф is UTF8? YES
2 год2020.рф
3 год2020.рф abc
Wide character in warn at /tmp/a.pl line 18.
4 Ð³Ð¾Ð´2020.ÑÑ
                рф
5 Ð³Ð¾Ð´2020.ÑÑ

6 http://год2020.рф
```
Although the `$host` says it is utf8, it still gets mutilated by `encode()`...

**Comment by sysread** [comment]
That's... strange. Does `URI::Fast::encode()` treat it differently?

**Comment by markov2** [comment]
I think I really understand UTF8 in Perl space, handling it correctly in my own complex modules, but after two hours trying I still did not understand why is_utf8 is true, but situations 4 and 5 fail.  It seems to be something strange in XS space.  I hate XS...

Probably you are smarter than me.

**Comment by sysread** [comment]
Almost certainly not. My wife confirms that statement.

**Comment by sysread** [comment]
I am not sure why this change fixed it. I still need to do some investigating to make sure I really understand what's going on here. Regardless, I might as well push the latest changes to cpan so you can make use of them.
