### ISSUE TITLE
please consider comparing with IRI

### ISSUE THREAD

**Issue by jonassmedegaard** [sysread/URI-Fast#5]
Hi,

Would be interesting if POD and benchmarks included comparison with the IRI module.

**Comment by sysread** [comment]
While URI::Fast supports utf8, I have not dug deeply enough into the IRI standard to know if it is even fully compliant. If you'd like to submit a unit test to verify equivalence and support for the standard, I'd be happy to look into making that support official and adding IRI to the benchmarks.

**Comment by jonassmedegaard** [comment]
I am no expert in the standard either. I have suggested kasei (author of IRI) on irc to consider helping out here.

**Comment by kasei** [comment]
I'm not entirely sure what the issue here is, but I can say that I wrote the IRI module because URI couldn't properly handle IRIs with unicode data. My needs (for the RDF::Query and Attean projects) are fairly limited when it comes to IRIs, though – mostly constructing absolute IRIs from a base and a relative IRI, and comparing two different IRI objects. There's not much support for more complex operations that URI supports, so a fair comparison between the two modules might be difficult.

**Comment by sysread** [comment]
IRIs and URIs handle utf8 in fundamentally different ways. For example, when assigning a new host name, a URI will percent-encode utf8 characters while an IRI will not. I don't see a clear way to support both that would not overly complicate the code or result in a significant performance penalty for non-IRI use.

That said, `uri_split` and `uri` will accept utf8 characters in the input string. A `URI::Fast` instance will not encode those values unless they are overwritten by a setter method (`URI::Fast` is intentionally flexible on input strings). However, once they are set, they will be percent-encoded to conform to the URI standard.

Let me think on this. Perhaps a flag on the `uri_t` struct that signals that it was created as an IRI and that utf8 characters should not be encoded. I'll do some testing to verify that this would not unnecessarily slow down the module for standard URIs.

**Comment by sysread** [comment]
@kasei Would you mind having a look at [this branch](https://github.com/sysread/URI-Fast/tree/iri-support)? I'm still benchmarking and verifying the changes, but I believe that should suit your needs.

**Comment by sysread** [comment]
I just pushed 0.23 to CPAN with IRI support and updated benchmarks.

**Comment by jonassmedegaard** [comment]
Great!
